import type { CollegeData } from "./college-api"
import { loadScholarshipsFromCSV, isDuplicateScholarship } from "./scholarship-data-loader"
import { loadSeedsOfFortuneScholarships, updateExistingScholarshipDates } from "./seeds-of-fortune-parser"

export interface ScholarshipData {
  id: string
  name: string
  description: string
  amount: string
  deadline: string
  type: "need-based" | "merit" | "demographic" | "program-specific" | "geographic"
  eligibility: string[]
  states: string[]
  colleges: string[]
  programs: string[]
  demographics: string[]
  website?: string
  provider: string
}

// Base scholarship database (existing scholarships)
const baseScholarshipDatabase: ScholarshipData[] = [
  // Federal Scholarships
  {
    id: "pell-grant",
    name: "Federal Pell Grant",
    description: "Need-based federal grant for undergraduate students",
    amount: "Up to $7,395",
    deadline: "June 30, 2025",
    type: "need-based",
    eligibility: ["Financial Need", "US Citizen", "Undergraduate"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "US Department of Education",
    website: "https://studentaid.gov/understand-aid/types/grants/pell",
  },
  {
    id: "teach-grant",
    name: "TEACH Grant",
    description: "Federal grant for future teachers",
    amount: "Up to $4,000",
    deadline: "Varies by school",
    type: "program-specific",
    eligibility: ["Education Major", "Teaching Commitment", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Education"],
    demographics: ["ALL"],
    provider: "US Department of Education",
    website: "https://studentaid.gov/understand-aid/types/grants/teach",
  },

  // Major Full-Ride Scholarships
  {
    id: "bryan-cameron-impact",
    name: "Bryan Cameron Impact Foundation Scholarship",
    description:
      "Full-ride scholarship for high school seniors demonstrating academic excellence and leadership potential",
    amount: "Full Ride",
    deadline: "February 1, 2025",
    type: "merit",
    eligibility: ["High School Senior", "Academic Excellence", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Bryan Cameron Impact Foundation",
    website: "https://www.bryancameronimpact.org/",
  },
  {
    id: "coolidge-scholars",
    name: "Coolidge Scholars Program",
    description: "Full-ride scholarship for high school juniors with exceptional academic achievement and leadership",
    amount: "Full Ride",
    deadline: "January 18, 2025",
    type: "merit",
    eligibility: ["High School Junior", "Academic Excellence", "Leadership", "Character"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Coolidge Presidential Foundation",
    website: "https://coolidgescholars.org/",
  },
  {
    id: "science-ambassador",
    name: "Science Ambassador Scholarship",
    description: "Full-ride scholarship for women and non-binary students pursuing STEM fields",
    amount: "Full Ride",
    deadline: "December 1, 2025",
    type: "demographic",
    eligibility: ["STEM Major", "Women/Non-Binary", "High School Senior or Undergraduate"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology"],
    demographics: ["Women", "Non-Binary"],
    provider: "Cards Against Humanity",
    website: "https://www.scienceambassadorscholarship.org/",
  },
  {
    id: "jack-kent-cooke",
    name: "Jack Kent Cooke Foundation Scholarship",
    description: "Full-ride scholarship for high-achieving students with financial need",
    amount: "Full Ride",
    deadline: "November 16, 2025",
    type: "need-based",
    eligibility: ["High School Senior", "High Academic Achievement", "Family Income Under $95,000"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Jack Kent Cooke Foundation",
    website: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
  },
  {
    id: "gates-millennium",
    name: "Gates Millennium Scholars Program",
    description: "Full scholarship for outstanding minority students through graduate school",
    amount: "Full Ride",
    deadline: "Varies",
    type: "demographic",
    eligibility: ["High Academic Achievement", "Leadership", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["African American", "American Indian", "Asian Pacific Islander", "Hispanic"],
    provider: "Gates Foundation",
    website: "https://gmsp.org/",
  },
  {
    id: "posse-scholars",
    name: "Posse Foundation Scholarship",
    description: "Full tuition scholarship for diverse student leaders at select universities",
    amount: "Full Tuition",
    deadline: "Varies by city",
    type: "demographic",
    eligibility: ["Leadership", "Academic Potential", "Diverse Background"],
    states: ["ALL"],
    colleges: ["Select Partner Universities"],
    programs: ["Arts", "STEM", "Liberal Arts"],
    demographics: ["Diverse Students"],
    provider: "Posse Foundation",
    website: "https://www.possefoundation.org/",
  },
  {
    id: "smart-scholarship",
    name: "SMART Scholarship",
    description: "Full ride scholarship for STEM students with government service commitment",
    amount: "Full Ride",
    deadline: "December 1, 2025",
    type: "program-specific",
    eligibility: ["STEM Major", "US Citizen", "Government Service Commitment"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Engineering", "Computer Science", "Mathematics", "Physics", "Chemistry"],
    demographics: ["ALL"],
    provider: "Department of Defense",
    website: "https://www.smartscholarship.org/smart",
  },

  // High-Value Scholarships ($50,000+)
  {
    id: "truman-scholarship",
    name: "Harry S. Truman Scholarship",
    description: "Premier graduate school scholarship for college juniors pursuing public service careers",
    amount: "$30,000",
    deadline: "February 1, 2025",
    type: "merit",
    eligibility: ["College Junior", "Public Service Interest", "Leadership", "Academic Excellence"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Public Service", "Government", "Non-Profit", "Education"],
    demographics: ["ALL"],
    provider: "Harry S. Truman Scholarship Foundation",
    website: "https://www.truman.gov/",
  },
  {
    id: "dr-pepper-scholarship",
    name: "Dr Pepper Scholarship",
    description: "Tuition giveaway for students aged 18-24",
    amount: "$100,000",
    deadline: "October 11, 2025",
    type: "merit",
    eligibility: ["Ages 18-24", "Video Submission", "Academic Goals"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Dr Pepper",
    website: "https://www.drpeppertuition.com/",
  },
  {
    id: "mcdonalds-hacer",
    name: "McDonald's HACER Scholarship",
    description: "Scholarships for Hispanic students with academic merit and financial need",
    amount: "$100,000",
    deadline: "February 5, 2025",
    type: "demographic",
    eligibility: ["Hispanic Heritage", "Academic Merit", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Hispanic"],
    provider: "McDonald's Corporation",
    website: "https://www.mcdonalds.com/us/en-us/community/hacer-scholarship.html",
  },
  {
    id: "hagan-scholarship",
    name: "Hagan Scholarship",
    description: "Eight-semester scholarship for rural students with financial need",
    amount: "$60,000",
    deadline: "March 1, 2025",
    type: "need-based",
    eligibility: ["High School Senior", "Rural Background", "Family Income Under $100,000"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Rural Students"],
    provider: "Hagan Scholarship Foundation",
    website: "https://haganscholarships.org/",
  },
  {
    id: "burger-king-scholarship",
    name: "Burger King Scholars Program",
    description: "Scholarships for high school seniors with academic achievement and work experience",
    amount: "$60,000",
    deadline: "December 15, 2025",
    type: "merit",
    eligibility: ["High School Senior", "Academic Achievement", "Work Experience"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Burger King Foundation",
    website: "https://www.burgerkingscholarship.com/",
  },
  {
    id: "davidson-fellows",
    name: "Davidson Fellows Scholarship",
    description:
      "Scholarship recognizing extraordinary young people for significant work in STEM, literature, music, or philosophy",
    amount: "$50,000",
    deadline: "February 14, 2025",
    type: "merit",
    eligibility: ["Age 18 and Under", "Extraordinary Achievement", "Research Project"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["STEM", "Literature", "Music", "Philosophy"],
    demographics: ["ALL"],
    provider: "Davidson Institute for Talent Development",
    website: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
  },
  {
    id: "sphinx-music",
    name: "Sphinx Music Scholarship",
    description: "Scholarships for Black and Latinx string players",
    amount: "$50,000",
    deadline: "January 24-27, 2025",
    type: "demographic",
    eligibility: ["String Player", "Musical Excellence"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Music"],
    demographics: ["Black", "Latinx"],
    provider: "Sphinx Organization",
    website: "https://www.sphinxmusic.org/",
  },

  // Major Merit Scholarships ($20,000-$50,000)
  {
    id: "aspfm-scholarship",
    name: "ASPFM Scholarship",
    description: "Scholarship for undergraduate students pursuing medical careers",
    amount: "$40,000",
    deadline: "February 1, 2025",
    type: "program-specific",
    eligibility: ["Undergraduate", "Pre-Med Track", "Essay Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Medicine", "Healthcare"],
    demographics: ["ALL"],
    provider: "American Society of Plastic and Reconstructive Surgeons",
    website: "https://www.aspfm.org/",
  },
  {
    id: "dream-us-national",
    name: "Dream.US National Scholarship",
    description: "Scholarships for immigrant students pursuing higher education",
    amount: "$39,000",
    deadline: "February 29, 2025",
    type: "demographic",
    eligibility: ["Immigrant Status", "DACA Recipients", "Academic Merit"],
    states: ["ALL"],
    colleges: ["Partner Colleges"],
    programs: ["ALL"],
    demographics: ["Immigrants"],
    provider: "TheDream.US",
    website: "https://www.thedream.us/",
  },
  {
    id: "jackie-robinson-foundation",
    name: "Jackie Robinson Foundation Scholarship",
    description: "Four-year scholarship for minority students with leadership potential",
    amount: "$35,000",
    deadline: "January 10, 2025",
    type: "demographic",
    eligibility: ["Minority Student", "Leadership", "Academic Merit", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["People of Color"],
    provider: "Jackie Robinson Foundation",
    website: "https://www.jackierobinson.org/",
  },
  {
    id: "vfw-youth-scholarship",
    name: "VFW Youth Scholarship",
    description: "Various scholarships for high school students with patriotic themes",
    amount: "$35,000",
    deadline: "October 31, 2025",
    type: "merit",
    eligibility: ["High School Student", "Patriotic Essay", "Community Service"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Veterans of Foreign Wars",
    website: "https://www.vfw.org/community/youth-and-education",
  },
  {
    id: "beinecke-scholarship",
    name: "Beinecke Scholarship",
    description: "Graduate school funding for students in arts, humanities, and social sciences",
    amount: "$35,000",
    deadline: "March 29, 2025",
    type: "program-specific",
    eligibility: ["College Junior", "Arts/Humanities/Social Sciences", "Faculty Nomination"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Arts", "Humanities", "Social Sciences"],
    demographics: ["ALL"],
    provider: "Sperry Fund",
    website: "https://beineckescholarship.org/",
  },
  {
    id: "elks-national-foundation",
    name: "Elks National Foundation Scholarship",
    description: "Merit-based scholarships for high school seniors",
    amount: "$30,000",
    deadline: "November 13, 2025",
    type: "merit",
    eligibility: ["High School Senior", "Academic Merit", "Leadership", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Elks National Foundation",
    website: "https://www.elks.org/scholars/",
  },
  {
    id: "doodle-for-google",
    name: "Doodle for Google Scholarship",
    description: "Art contest and scholarship for K-12 students to create a Google Doodle",
    amount: "$30,000",
    deadline: "March 1, 2025",
    type: "program-specific",
    eligibility: ["K-12 Student", "Artistic Ability", "Creativity"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Arts", "Design", "Creative"],
    demographics: ["ALL"],
    provider: "Google",
    website: "https://doodles.google.com/d4g/",
  },
  {
    id: "rl-rosenberg-poetry",
    name: "RL+DS Rosenberg Poetry Fellowship",
    description: "Fellowship for poets aged 21 and older",
    amount: "$27,000",
    deadline: "April 1, 2025",
    type: "program-specific",
    eligibility: ["Age 21+", "Poetry Portfolio", "Literary Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Creative Writing", "Poetry"],
    demographics: ["ALL"],
    provider: "Rosenberg Foundation",
    website: "https://www.poetryfellowship.org/",
  },
  {
    id: "legion-oratorical",
    name: "American Legion Oratorical Contest",
    description: "Constitutional oratory contest for high school students",
    amount: "$25,000",
    deadline: "State-dependent",
    type: "merit",
    eligibility: ["High School Student", "Oratory Skills", "Constitutional Knowledge"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Government", "Political Science", "Communications"],
    demographics: ["ALL"],
    provider: "American Legion",
    website: "https://www.legion.org/oratorical",
  },
  {
    id: "horatio-alger",
    name: "Horatio Alger Scholarship",
    description: "For students who have overcome significant obstacles",
    amount: "$25,000",
    deadline: "March 15, 2025",
    type: "merit",
    eligibility: ["Financial Need", "Overcome Adversity", "Strong Character", "Family Income $65,000 or below"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Horatio Alger Association",
    website: "https://scholars.horatioalger.org/scholarships/",
  },
  {
    id: "chick-fil-a-scholarship",
    name: "Chick-fil-A Scholarship",
    description: "Scholarships for Chick-fil-A team members",
    amount: "$25,000",
    deadline: "October 18, 2025",
    type: "demographic",
    eligibility: ["Chick-fil-A Employee", "Academic Merit", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Chick-fil-A Employees"],
    provider: "Chick-fil-A Foundation",
    website: "https://www.chick-fil-afoundation.org/",
  },
  {
    id: "buick-scholarship",
    name: "Buick Achievers Scholarship",
    description: "Scholarships for students pursuing STEM or business degrees",
    amount: "$25,000",
    deadline: "February 28, 2025",
    type: "program-specific",
    eligibility: ["STEM or Business Major", "Academic Merit", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["STEM", "Business"],
    demographics: ["ALL"],
    provider: "General Motors",
    website: "https://www.buickachievers.com/",
  },
  {
    id: "axa-achievement",
    name: "AXA Achievement Scholarship",
    description: "Scholarship recognizing students who have overcome challenges to achieve success",
    amount: "$25,000",
    deadline: "December 15, 2025",
    type: "merit",
    eligibility: ["High School Senior", "Overcome Challenges", "Achievement", "Ambition"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "AXA Foundation",
    website: "https://www.axa-achievement.com/",
  },
  {
    id: "coca-cola-scholars",
    name: "Coca-Cola Scholars Program",
    description: "Recognizing exceptional high school seniors",
    amount: "$20,000",
    deadline: "October 31, 2025",
    type: "merit",
    eligibility: ["Leadership", "Community Service", "Academic Achievement"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Coca-Cola Foundation",
    website: "https://www.coca-colascholarsfoundation.org/apply/",
  },
  {
    id: "beyond-the-boroughs",
    name: "Beyond the Boroughs Scholarship",
    description: "Scholarship for New York City students pursuing higher education",
    amount: "$20,000",
    deadline: "March 15, 2025",
    type: "geographic",
    eligibility: ["New York City Resident", "High School Senior", "Academic Merit"],
    states: ["NY"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Beyond the Boroughs Foundation",
    website: "https://www.beyondtheboroughs.org/",
  },
  {
    id: "james-park-memorial",
    name: "James H Park Memorial Scholarship",
    description: "Scholarship for students with medical service experience",
    amount: "$20,000",
    deadline: "TBD",
    type: "program-specific",
    eligibility: ["Age 19+", "100+ Hours Medical Service", "Faculty Nomination"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Medicine", "Healthcare"],
    demographics: ["ALL"],
    provider: "James H Park Memorial Foundation",
    website: "https://www.jamesparkfoundation.org/",
  },
  {
    id: "engebretson-scholarship",
    name: "Engebretson Foundation Scholarship",
    description: "Merit-based scholarship for high school seniors",
    amount: "$20,000",
    deadline: "March 1, 2025",
    type: "merit",
    eligibility: ["High School Senior", "Academic Merit", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Engebretson Foundation",
    website: "https://www.engebretson.org/",
  },
  {
    id: "apia-scholars",
    name: "APIA Scholarship",
    description: "Scholarships for Asian Pacific Islander Americans",
    amount: "$20,000",
    deadline: "January 9, 2025",
    type: "demographic",
    eligibility: ["Asian Pacific Islander", "Financial Need", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Asian Pacific Islander"],
    provider: "APIA Scholars",
    website: "https://www.apiascholars.org/scholarships/",
  },
  {
    id: "dell-scholars",
    name: "Dell Scholars Program",
    description: "Supporting students who have overcome significant obstacles",
    amount: "$20,000",
    deadline: "January 27, 2025",
    type: "merit",
    eligibility: ["High School Junior/Senior", "College Readiness Program", "Overcome Obstacles"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Michael & Susan Dell Foundation",
    website: "https://www.dellscholars.org/scholarship/",
  },
  {
    id: "us-bank-scholarship",
    name: "U.S. Bank Student Scholarship",
    description: "Scholarship for students demonstrating academic achievement",
    amount: "$20,000",
    deadline: "October 30, 2025",
    type: "merit",
    eligibility: ["Age 17+", "Academic Merit", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "U.S. Bank",
    website: "https://www.usbank.com/about-us-bank/community/student-scholarship.html",
  },
  {
    id: "swe-scholarships",
    name: "Society of Women Engineers Scholarships",
    description: "Scholarships for women in engineering",
    amount: "$20,000",
    deadline: "January-March 2025",
    type: "demographic",
    eligibility: ["Women", "Engineering Major", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Engineering"],
    demographics: ["Women"],
    provider: "Society of Women Engineers",
    website: "https://swe.org/scholarships/",
  },

  // Medium-Value Scholarships ($10,000-$20,000)
  {
    id: "davis-putter-scholarship",
    name: "Davis-Putter Scholarship",
    description: "Scholarships for students involved in social justice movements",
    amount: "$15,000",
    deadline: "April 1, 2025",
    type: "merit",
    eligibility: ["Undergraduate", "Social Justice Involvement", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Davis-Putter Scholarship Fund",
    website: "https://www.davisputter.org/",
  },
  {
    id: "barry-goldwater",
    name: "Barry Goldwater Scholarship",
    description: "Premier scholarship for sophomores and juniors pursuing research careers in STEM fields",
    amount: "$7,500",
    deadline: "January 31, 2025",
    type: "merit",
    eligibility: ["College Sophomore/Junior", "STEM Research Interest", "Faculty Nomination Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Mathematics", "Natural Sciences", "Engineering"],
    demographics: ["ALL"],
    provider: "Barry Goldwater Scholarship Foundation",
    website: "https://goldwaterscholarship.gov/",
  },
  {
    id: "prudential-emerging-visionaries",
    name: "Prudential Emerging Visionaries",
    description: "Scholarship for young social entrepreneurs making a difference in their communities",
    amount: "$15,000",
    deadline: "November 2, 2025",
    type: "merit",
    eligibility: ["Ages 14-18", "Social Entrepreneurship", "Community Impact"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Social Entrepreneurship", "Community Service"],
    demographics: ["ALL"],
    provider: "Prudential Financial",
    website: "https://www.prudential.com/about/corporate-social-responsibility/prudential-emerging-visionaries",
  },
  {
    id: "vegetarian-resource-group",
    name: "Vegetarian Resource Group Scholarship",
    description: "Scholarships for students promoting vegetarianism",
    amount: "$10,000",
    deadline: "February 20, 2025",
    type: "program-specific",
    eligibility: ["High School Senior", "Vegetarian Advocacy", "Community Service"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Environmental Studies", "Nutrition", "Animal Rights"],
    demographics: ["ALL"],
    provider: "Vegetarian Resource Group",
    website: "https://www.vrg.org/student/scholar.htm",
  },
  {
    id: "thermo-fisher-scientific",
    name: "Thermo Fisher Scientific Scholarship",
    description: "STEM scholarship for high school seniors",
    amount: "$10,000",
    deadline: "May 1, 2025",
    type: "program-specific",
    eligibility: ["High School Senior", "STEM Major", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["STEM", "Science", "Technology"],
    demographics: ["ALL"],
    provider: "Thermo Fisher Scientific",
    website: "https://www.thermofisher.com/us/en/home/about-us/corporate-responsibility/stem-education.html",
  },
  {
    id: "unigo-scholarships",
    name: "Unigo Scholarships",
    description: "Various scholarships with short answer questions",
    amount: "$10,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 14+", "Short Essays", "Academic Goals"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Unigo",
    website: "https://www.unigo.com/scholarships",
  },
  {
    id: "us-creative-writing",
    name: "U.S. Creative Writing Scholarship",
    description: "Scholarship for high school seniors pursuing creative writing",
    amount: "$10,000",
    deadline: "October 2025",
    type: "program-specific",
    eligibility: ["High School Senior", "Creative Writing Portfolio", "Literary Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Creative Writing", "English", "Literature"],
    demographics: ["ALL"],
    provider: "Creative Writing Foundation",
    website: "https://www.creativewritingscholarship.org/",
  },
  {
    id: "gloria-barron-prize",
    name: "Gloria Barron Prize for Young Heroes",
    description: "Awards for young people making a positive impact on communities and environment",
    amount: "$10,000",
    deadline: "April 15, 2025",
    type: "merit",
    eligibility: ["Ages 8-18", "Community Impact", "Environmental/Social Project"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Environmental Studies", "Community Service"],
    demographics: ["ALL"],
    provider: "Barron Prize",
    website: "https://barronprize.org/",
  },
  {
    id: "jfk-profile-courage",
    name: "JFK Profile in Courage Essay Contest",
    description: "Essay contest about political courage",
    amount: "$10,000",
    deadline: "January 12, 2025",
    type: "program-specific",
    eligibility: ["Grades 9-12", "Essay about US Elected Official", "Historical Analysis"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["History", "Political Science", "Government"],
    demographics: ["ALL"],
    provider: "JFK Library Foundation",
    website: "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
  },
  {
    id: "greeting-card-scholarship",
    name: "Greeting Card Scholarship",
    description: "Creative scholarship for designing greeting cards",
    amount: "$10,000",
    deadline: "March 1, 2025",
    type: "program-specific",
    eligibility: ["Age 14+", "Creative Design", "Greeting Card Submission"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Arts", "Design", "Creative"],
    demographics: ["ALL"],
    provider: "Gallery Collection",
    website: "https://www.gallerycollection.com/greeting-cards-scholarship.htm",
  },
  {
    id: "potato-scholars",
    name: "Potato Scholarship",
    description: "Scholarship for graduate students researching potato-related topics",
    amount: "$10,000",
    deadline: "TBD",
    type: "program-specific",
    eligibility: ["Graduate Student", "Potato Research Interest", "Agricultural Studies"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Agriculture", "Food Science", "Research"],
    demographics: ["ALL"],
    provider: "National Potato Council",
    website: "https://nationalpotatocouncil.org/",
  },
  {
    id: "exploravision-science",
    name: "ExploraVision Science Competition",
    description: "STEM competition for K-12 students",
    amount: "$10,000",
    deadline: "January 31, 2025",
    type: "program-specific",
    eligibility: ["K-12 Student", "STEM Project", "Team Competition"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["STEM", "Science", "Technology"],
    demographics: ["ALL"],
    provider: "Toshiba/NSTA",
    website: "https://www.exploravision.org/",
  },
  {
    id: "aanapisi-scholars",
    name: "AANAPISI Scholars",
    description: "Scholarships for Asian American, Native American, and Pacific Islander students",
    amount: "$10,000",
    deadline: "January 9, 2025",
    type: "demographic",
    eligibility: ["Asian American", "Native American", "Pacific Islander", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Asian American", "Native American", "Pacific Islander"],
    provider: "AANAPISI",
    website: "https://www.aanapisi.org/",
  },
  {
    id: "graduate-women-science",
    name: "Graduate Women in Science Fellowship",
    description: "Fellowship for women pursuing graduate degrees in STEM",
    amount: "$10,000",
    deadline: "January 8, 2025",
    type: "demographic",
    eligibility: ["Women", "Graduate Student", "STEM Field"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["STEM", "Science", "Technology", "Engineering", "Mathematics"],
    demographics: ["Women"],
    provider: "Graduate Women in Science",
    website: "https://www.gwis.org/",
  },
  {
    id: "ussyp-scholarship",
    name: "United States Senate Youth Program",
    description: "Week-long Washington experience and scholarship for student leaders",
    amount: "$10,000",
    deadline: "Varies by State",
    type: "merit",
    eligibility: ["High School Junior/Senior", "Student Government Leadership", "Demonstrated Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Government", "Political Science", "Public Service"],
    demographics: ["ALL"],
    provider: "William Randolph Hearst Foundation",
    website: "https://ussenateyouth.org/",
  },

  // Smaller Scholarships ($1,000-$10,000)
  {
    id: "project-yellow-light",
    name: "Project Yellow Light Scholarship",
    description: "Creative contest promoting safe driving",
    amount: "$8,000",
    deadline: "April 1, 2025",
    type: "program-specific",
    eligibility: ["Ages 14-25", "Creative Project", "Safe Driving Advocacy"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Media", "Public Safety", "Creative"],
    demographics: ["ALL"],
    provider: "Project Yellow Light",
    website: "https://www.projectyellowlight.com/",
  },
  {
    id: "lindsey-vonn-foundation",
    name: "Lindsey Vonn Foundation Scholarship",
    description: "Scholarships for young women in sports and education",
    amount: "$5,000",
    deadline: "March 31, 2025",
    type: "demographic",
    eligibility: ["Female", "Ages 10-18", "Athletic or Academic Achievement"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Sports", "Education"],
    demographics: ["Women"],
    provider: "Lindsey Vonn Foundation",
    website: "https://www.lindseyvonn.com/foundation",
  },
  {
    id: "american-college-foundation",
    name: "American College Foundation Scholarship",
    description: "Merit-based scholarship for grades 9-12",
    amount: "$5,000",
    deadline: "June 1, 2025",
    type: "merit",
    eligibility: ["Grades 9-12", "Academic Merit", "Essay Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "American College Foundation",
    website: "https://americancollegefoundation.org/",
  },
  {
    id: "ron-hubbard-contest",
    name: "L. Ron Hubbard Writers of the Future Contest",
    description: "Writing contest for aspiring science fiction and fantasy writers",
    amount: "$5,000",
    deadline: "Quarterly",
    type: "program-specific",
    eligibility: ["Unpublished Writer", "Science Fiction/Fantasy", "Short Story Submission"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Creative Writing", "Literature"],
    demographics: ["ALL"],
    provider: "L. Ron Hubbard Foundation",
    website: "https://www.writersofthefuture.com/",
  },
  {
    id: "ayn-rand-essay",
    name: "Ayn Rand Essay Competition",
    description: "Essay contest based on Ayn Rand novels",
    amount: "$5,000",
    deadline: "April 25, 2025",
    type: "program-specific",
    eligibility: ["Grades 8-12", "Essay on Ayn Rand Novel", "Literary Analysis"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Literature", "Philosophy", "Writing"],
    demographics: ["ALL"],
    provider: "Ayn Rand Institute",
    website: "https://www.aynrand.org/students/essay-contests",
  },
  {
    id: "sara-scholarship",
    name: "Sara Scholarship",
    description: "Scholarship for female students involved in golf",
    amount: "$2,500",
    deadline: "April 30, 2025",
    type: "demographic",
    eligibility: ["Female", "High School Senior", "Golf Involvement"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Sports Management", "Recreation"],
    demographics: ["Women"],
    provider: "Sara Foundation",
    website: "https://www.sarafoundation.org/",
  },
  {
    id: "stossel-classroom",
    name: "Stossel in the Classroom",
    description: "Essay contest on economic and political topics",
    amount: "$2,500",
    deadline: "March 22, 2025",
    type: "program-specific",
    eligibility: ["Middle/High School", "Economics Essay", "Critical Thinking"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Economics", "Political Science"],
    demographics: ["ALL"],
    provider: "Stossel Education",
    website: "https://www.stosseleducation.org/",
  },
  {
    id: "american-red-cross",
    name: "American Red Cross Scholarship",
    description: "Scholarship for students who organize blood drives",
    amount: "$2,500",
    deadline: "August 31, 2025",
    type: "program-specific",
    eligibility: ["High School/Undergraduate", "Blood Drive Organization", "Community Service"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Healthcare", "Community Service"],
    demographics: ["ALL"],
    provider: "American Red Cross",
    website: "https://www.redcross.org/about-us/our-work/international-services/scholarships",
  },
  {
    id: "james-cox-foundation",
    name: "James Alan Cox Foundation Scholarship",
    description: "Various scholarships for students with different requirements",
    amount: "$2,500",
    deadline: "July 15, 2025",
    type: "merit",
    eligibility: ["High School/Undergraduate/Graduate", "Various Requirements", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "James Alan Cox Foundation",
    website: "https://www.jamescoxfoundation.org/",
  },
  {
    id: "scholarship-points",
    name: "ScholarshipPoints",
    description: "Monthly scholarship drawings for students",
    amount: "$2,500",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 13+", "Student Status", "Monthly Entry"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "ScholarshipPoints",
    website: "https://www.scholarshippoints.com/",
  },
  {
    id: "smarter-college",
    name: "SmarterCollege Scholarship",
    description: "Monthly scholarship for college-bound students",
    amount: "$2,500",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 17+", "College-Bound", "Monthly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "SmarterCollege",
    website: "https://www.smartercollege.com/",
  },
  {
    id: "nitro-scholarship",
    name: "Nitro Scholarship",
    description: "Monthly scholarship for students",
    amount: "$2,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 17+", "Student Status", "Monthly Entry"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Nitro",
    website: "https://www.nitrocollege.com/scholarships",
  },
  {
    id: "campus-reel",
    name: "CampusReel Scholarship",
    description: "Scholarship for watching student tour videos",
    amount: "$2,000",
    deadline: "Ongoing",
    type: "merit",
    eligibility: ["High School Freshman+", "Watch Student Tours", "College Interest"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "CampusReel",
    website: "https://www.campusreel.org/",
  },
  {
    id: "niche-no-essay",
    name: "Niche No Essay Scholarship",
    description: "Monthly scholarship with no essay required",
    amount: "$2,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["High School/Undergraduate", "No Essay Required", "Monthly Drawing"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Niche",
    website: "https://www.niche.com/colleges/scholarships/no-essay-scholarship/",
  },
  {
    id: "sallie-mae-scholarship",
    name: "Sallie Mae Scholarship",
    description: "Scholarship for high school juniors and undergraduates",
    amount: "$2,000",
    deadline: "December 31, 2025",
    type: "merit",
    eligibility: ["High School Junior/Undergraduate", "Academic Merit", "Financial Need"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Sallie Mae",
    website: "https://www.salliemae.com/college-planning/scholarships/",
  },
  {
    id: "collegevine-scholarships",
    name: "CollegeVine Scholarships",
    description: "Quarterly scholarships for high school students",
    amount: "$2,000",
    deadline: "Quarterly",
    type: "merit",
    eligibility: ["High School Student", "College Planning", "Academic Goals"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "CollegeVine",
    website: "https://www.collegevine.com/scholarships",
  },
  {
    id: "zombie-apocalypse",
    name: "Zombie Apocalypse Scholarship",
    description: "Creative scholarship about surviving a zombie apocalypse at school",
    amount: "$2,000",
    deadline: "March 31, 2025",
    type: "program-specific",
    eligibility: ["Age 14+", "Creative Writing", "Zombie Survival Plan"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Creative Writing", "Creative"],
    demographics: ["ALL"],
    provider: "Unigo",
    website: "https://www.unigo.com/scholarships/our-scholarships/zombie-apocalypse-scholarship",
  },
  {
    id: "minecraft-scholarship",
    name: "Minecraft Scholarship",
    description: "Scholarship for students who play Minecraft",
    amount: "$2,000",
    deadline: "July 31, 2025",
    type: "program-specific",
    eligibility: ["High School/Undergraduate", "Minecraft Player", "Gaming Interest"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Game Design", "Technology"],
    demographics: ["ALL"],
    provider: "Apex Mining",
    website: "https://www.apexminecrafthosting.com/scholarship/",
  },
  {
    id: "fbusa-scholarship",
    name: "FBUSA Scholarship",
    description: "Monthly scholarship for high school seniors and undergraduates",
    amount: "$2,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["High School Senior/Undergraduate", "Academic Merit", "Monthly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "FBUSA",
    website: "https://www.fbusa.org/",
  },
  {
    id: "realty-hop",
    name: "RealtyHop Scholarship",
    description: "Bi-annual scholarship for high school seniors and undergraduates",
    amount: "$2,000",
    deadline: "April 30 & August 31, 2025",
    type: "merit",
    eligibility: ["High School Senior/Undergraduate", "Essay Required", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "RealtyHop",
    website: "https://www.realtyhop.com/scholarship",
  },
  {
    id: "frame-my-future",
    name: "Frame My Future Scholarship",
    description: "Scholarship for creating TikTok videos about your future",
    amount: "$2,000",
    deadline: "March 15, 2025",
    type: "program-specific",
    eligibility: ["Undergraduate", "TikTok Video", "Future Goals"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Media", "Communications"],
    demographics: ["ALL"],
    provider: "Church Hill Classics",
    website: "https://www.diplomaframe.com/frame-my-future-scholarship.aspx",
  },
  {
    id: "courageous-persuaders",
    name: "Courageous Persuaders Scholarship",
    description: "Scholarship for creating commercials about safe driving",
    amount: "$2,000",
    deadline: "March 11, 2025",
    type: "program-specific",
    eligibility: ["High School Student", "30-Second Commercial", "Safe Driving Message"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Media", "Public Safety"],
    demographics: ["ALL"],
    provider: "Courageous Persuaders",
    website: "https://www.courageouspersuaders.com/",
  },

  // Small Scholarships ($500-$1,500)
  {
    id: "ocean-awareness",
    name: "Ocean Awareness Contest",
    description: "Contest promoting ocean conservation awareness",
    amount: "$1,500",
    deadline: "June 10, 2025",
    type: "program-specific",
    eligibility: ["Ages 11-18", "Ocean Conservation", "Creative Project"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Environmental Science", "Marine Biology"],
    demographics: ["ALL"],
    provider: "Bow Seat Ocean Awareness Programs",
    website: "https://www.bowseat.org/programs/ocean-awareness-contest/",
  },
  {
    id: "cri-scholarship",
    name: "CRI Scholarship",
    description: "Scholarship for creating design or video content",
    amount: "$1,500",
    deadline: "April 25, 2025",
    type: "program-specific",
    eligibility: ["Ages 14-22", "Design/Video Creation", "Creative Skills"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Design", "Media", "Arts"],
    demographics: ["ALL"],
    provider: "CRI Foundation",
    website: "https://www.crifoundation.org/",
  },
  {
    id: "americanism-essay",
    name: "Americanism Essay Contest",
    description: "Essay contest promoting American values",
    amount: "$1,500",
    deadline: "December 1, 2025",
    type: "program-specific",
    eligibility: ["Grades 7-12", "Patriotic Essay", "American Values"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["History", "Government", "Writing"],
    demographics: ["ALL"],
    provider: "American Legion Auxiliary",
    website: "https://www.alaforveterans.org/",
  },
  {
    id: "au-essay-contest",
    name: "AU Essay Contest",
    description: "Essay contest on church-state separation",
    amount: "$1,500",
    deadline: "TBD 2025",
    type: "program-specific",
    eligibility: ["High School Junior/Senior", "750-1000 Words", "Constitutional Issues"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Government", "Political Science", "Law"],
    demographics: ["ALL"],
    provider: "Americans United for Separation of Church and State",
    website: "https://www.au.org/",
  },
  {
    id: "bezos-scholars",
    name: "Bezos Scholars Program",
    description: "Leadership program with scholarship for high school juniors",
    amount: "$1,000",
    deadline: "January 25, 2025",
    type: "merit",
    eligibility: ["High School Junior", "Leadership Potential", "College Advising"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Leadership", "ALL"],
    demographics: ["ALL"],
    provider: "Bezos Family Foundation",
    website: "https://www.bezosfamilyfoundation.org/",
  },
  {
    id: "alex-hamilton-awards",
    name: "Alexander Hamilton Awards",
    description: "Awards for high school juniors interested in government",
    amount: "$1,000",
    deadline: "January 31, 2025",
    type: "program-specific",
    eligibility: ["High School Junior", "Government Interest", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Government", "Political Science"],
    demographics: ["ALL"],
    provider: "Alexander Hamilton Society",
    website: "https://www.alexanderhamilton.org/",
  },
  {
    id: "cancer-unwrapped",
    name: "Cancer Unwrapped Scholarship",
    description: "Scholarship for students affected by cancer",
    amount: "$1,000",
    deadline: "March 2, 2025",
    type: "program-specific",
    eligibility: ["Grades 9-12", "Cancer Experience", "Personal Essay"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Healthcare", "Medicine"],
    demographics: ["ALL"],
    provider: "Cancer Unwrapped",
    website: "https://www.cancerunwrapped.com/",
  },
  {
    id: "grhs-essay",
    name: "GRHS Essay Scholarship",
    description: "Scholarship for students with German or Russian heritage",
    amount: "$1,000",
    deadline: "March 31, 2025",
    type: "demographic",
    eligibility: ["Grades 6-Undergraduate", "German/Russian Heritage", "Cultural Essay"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Cultural Studies", "History"],
    demographics: ["German Heritage", "Russian Heritage"],
    provider: "Germans from Russia Heritage Society",
    website: "https://www.grhs.org/",
  },
  {
    id: "jansa-essay",
    name: "JANSA Essay Contest",
    description: "Jane Austen essay contest for high school students",
    amount: "$1,000",
    deadline: "June 1, 2025",
    type: "program-specific",
    eligibility: ["High School Student", "Jane Austen Essay", "6-8 Pages"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Literature", "English", "Writing"],
    demographics: ["ALL"],
    provider: "Jane Austen Society of North America",
    website: "https://www.jasna.org/",
  },
  {
    id: "cip-scholarship",
    name: "CIP Scholarship",
    description: "Monthly scholarship asking why you want to go to school",
    amount: "$1,000",
    deadline: "March 31, 2025",
    type: "merit",
    eligibility: ["Age 17+", "College Goals", "Short Essay"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "College Incentive Program",
    website: "https://www.cipscholarship.org/",
  },
  {
    id: "gen-kelly-scholarship",
    name: "Gen Kelly Scholarship",
    description: "Scholarship for students with military connections",
    amount: "$1,000",
    deadline: "July 31, 2025",
    type: "demographic",
    eligibility: ["High School Freshman-Adult", "Military Connection", "250 Words"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Military Family"],
    provider: "Gen Kelly Foundation",
    website: "https://www.genkellyfoundation.org/",
  },
  {
    id: "sbo-scholarship",
    name: "SBO Scholarship",
    description: "Scholarship for students involved in music",
    amount: "$1,000",
    deadline: "March 31, 2025",
    type: "program-specific",
    eligibility: ["K-12", "Music Involvement", "250 Words"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Music", "Arts"],
    demographics: ["ALL"],
    provider: "School Band & Orchestra",
    website: "https://www.sbomagazine.com/",
  },
  {
    id: "carson-scholars",
    name: "Carson Scholars Fund",
    description: "Scholarship for students with academic achievement and humanitarian qualities",
    amount: "$1,000",
    deadline: "January 12, 2025",
    type: "merit",
    eligibility: ["Grades 4-11", "Academic Excellence", "Humanitarian Qualities", "School Nomination"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Carson Scholars Fund",
    website: "https://carsonscholars.org/",
  },
  {
    id: "working-student",
    name: "Working Student Scholarship",
    description: "Scholarship for undergraduate students who work",
    amount: "$1,000",
    deadline: "December 15, 2025",
    type: "merit",
    eligibility: ["Undergraduate", "Working Student", "500 Words"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Working Student Foundation",
    website: "https://www.workingstudent.org/",
  },
  {
    id: "dna-day-scholarship",
    name: "DNA Day Essay Contest",
    description: "Essay contest about genetics and genomics",
    amount: "$1,000",
    deadline: "March 2025",
    type: "program-specific",
    eligibility: ["High School Student", "Genetics Essay", "Scientific Knowledge"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Biology", "Genetics", "Science"],
    demographics: ["ALL"],
    provider: "American Society of Human Genetics",
    website: "https://www.ashg.org/education/dna-day/",
  },
  {
    id: "tall-club-scholarship",
    name: "Tall Club International Scholarship",
    description: "Scholarship for tall students",
    amount: "$1,000",
    deadline: "TBD",
    type: "demographic",
    eligibility: ["Undergraduate", "Height Requirements", "Academic Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["Tall Students"],
    provider: "Tall Club International",
    website: "https://www.tall.org/",
  },
  {
    id: "navin-narayan",
    name: "Navin Narayan College Scholarship",
    description: "Scholarship for high school seniors",
    amount: "$1,000",
    deadline: "February 2025",
    type: "merit",
    eligibility: ["High School Senior", "Academic Merit", "Essay Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Navin Narayan Foundation",
    website: "https://www.navinnarayan.org/",
  },
  {
    id: "against-all-odds",
    name: "Against All Odds Scholarship",
    description: "Scholarship for students who have overcome significant challenges",
    amount: "$1,000",
    deadline: "January 31, 2025",
    type: "merit",
    eligibility: ["Undergraduate", "Overcome Challenges", "Email Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Against All Odds Foundation",
    website: "https://www.againstallodds.org/",
  },
  {
    id: "carbrain-scholarship",
    name: "CarBrain Scholarship",
    description: "Essay scholarship about AI and the automotive industry",
    amount: "$1,000",
    deadline: "November 1, 2025",
    type: "program-specific",
    eligibility: ["Undergraduate", "AI/Automotive Essay", "Technology Interest"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Technology", "Engineering", "Business"],
    demographics: ["ALL"],
    provider: "CarBrain",
    website: "https://www.carbrain.com/scholarship",
  },
  {
    id: "dmvedu-scholarship",
    name: "DMVEdu Scholarship",
    description: "Scholarship for high school and undergraduate students",
    amount: "$1,000",
    deadline: "March 31, 2025",
    type: "merit",
    eligibility: ["High School/Undergraduate", "Academic Merit", "Essay Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "DMVEdu",
    website: "https://www.dmvedu.org/",
  },
  {
    id: "cappex-scholarship",
    name: "CappEx Easy Money Scholarship",
    description: "Monthly scholarship for students",
    amount: "$1,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 13+", "Student Status", "Monthly Entry"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "CappEx",
    website: "https://www.cappex.com/scholarships",
  },
  {
    id: "smarter-college-essay",
    name: "SmarterCollege Essay Scholarship",
    description: "Monthly essay scholarship",
    amount: "$1,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 16+", "Essay Required", "Monthly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "SmarterCollege",
    website: "https://www.smartercollege.com/",
  },
  {
    id: "super-college",
    name: "SuperCollege Scholarship",
    description: "Scholarship for high school seniors and undergraduates",
    amount: "$1,000",
    deadline: "January 31, 2025",
    type: "merit",
    eligibility: ["High School Senior/Undergraduate", "Academic Merit", "Essay Required"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "SuperCollege",
    website: "https://www.supercollege.com/scholarship/",
  },
  {
    id: "community-champ",
    name: "Community Champion Scholarship",
    description: "Scholarship for community service leaders",
    amount: "$1,000",
    deadline: "February 1, 2025",
    type: "merit",
    eligibility: ["Age 18+", "Community Service", "Leadership"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Community Service", "Leadership"],
    demographics: ["ALL"],
    provider: "Community Champions",
    website: "https://www.communitychampions.org/",
  },
  {
    id: "shining-star",
    name: "Shining Star Scholarship",
    description: "Monthly scholarship for outstanding students",
    amount: "$1,000",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["Age 18+", "Academic Excellence", "Monthly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Shining Star Foundation",
    website: "https://www.shiningstar.org/",
  },
  {
    id: "tc-school-scholarship",
    name: "TC School Scholarship",
    description: "Quarterly scholarship for high school freshmen and undergraduates",
    amount: "$1,000",
    deadline: "Quarterly",
    type: "merit",
    eligibility: ["High School Freshman/Undergraduate", "Academic Merit", "Quarterly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "TC School",
    website: "https://www.tcschool.org/",
  },
  {
    id: "api-scholarship",
    name: "API Scholarship",
    description: "Quarterly scholarship for high school students",
    amount: "$1,000",
    deadline: "Quarterly",
    type: "merit",
    eligibility: ["High School Student", "Academic Merit", "Quarterly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "API Foundation",
    website: "https://www.apifoundation.org/",
  },

  // Very Small Scholarships ($500 and under)
  {
    id: "national-hs-poetry",
    name: "National High School Poetry Contest",
    description: "Poetry contest for high school students",
    amount: "$500",
    deadline: "Quarterly",
    type: "program-specific",
    eligibility: ["High School Student", "20-Line Poem", "Literary Merit"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Creative Writing", "Poetry", "Literature"],
    demographics: ["ALL"],
    provider: "Poetry Society",
    website: "https://www.poetrysociety.org/",
  },
  {
    id: "1dental-scholarship",
    name: "1Dental Scholarship",
    description: "Scholarship for students interested in dental health",
    amount: "$500",
    deadline: "May 31, 2025",
    type: "program-specific",
    eligibility: ["High School Senior", "Dental Health Interest", "Short Answer Questions"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Dentistry", "Healthcare"],
    demographics: ["ALL"],
    provider: "1Dental",
    website: "https://www.1dental.com/scholarship/",
  },
  {
    id: "ctg-scholarship",
    name: "CTG Scholarship",
    description: "Monthly scholarship for high school juniors and seniors",
    amount: "$500",
    deadline: "Monthly",
    type: "merit",
    eligibility: ["High School Junior/Senior", "Essay Required", "Monthly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "CTG Foundation",
    website: "https://www.ctgfoundation.org/",
  },
  {
    id: "cie-scholarship",
    name: "CIE Scholarship",
    description: "Quarterly scholarship for students aged 16+",
    amount: "$500",
    deadline: "Quarterly",
    type: "merit",
    eligibility: ["Age 16+", "Academic Merit", "Quarterly Application"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "CIE Foundation",
    website: "https://www.ciefoundation.org/",
  },
  {
    id: "fontana-scholarship",
    name: "Fontana Scholarship Program",
    description: "Scholarship for first-generation college students",
    amount: "Varies",
    deadline: "March 14, 2025",
    type: "demographic",
    eligibility: ["High School Senior", "First Generation College Student", "Random Selection"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["First Generation"],
    provider: "Fontana Foundation",
    website: "https://www.fontanafoundation.org/",
  },

  // Special High-Value Scholarships
  {
    id: "breakthrough-junior-challenge",
    name: "Breakthrough Junior Challenge",
    description: "Science video competition for high school students",
    amount: "$250,000",
    deadline: "October 2025",
    type: "program-specific",
    eligibility: ["High School Student", "Science Video", "Creative Communication"],
    states: ["ALL"],
    colleges: ["ALL"],
    programs: ["Science", "STEM", "Communications"],
    demographics: ["ALL"],
    provider: "Breakthrough Prize Foundation",
    website: "https://breakthroughjuniorchallenge.org/",
  },

  // State-Specific Scholarships
  {
    id: "cal-grant-a",
    name: "Cal Grant A",
    description: "California grant covering tuition and fees",
    amount: "Up to $12,570",
    deadline: "March 2, 2025",
    type: "need-based",
    eligibility: ["California Resident", "Financial Need", "GPA 3.0+"],
    states: ["CA"],
    colleges: ["University of California", "California State University"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "California Student Aid Commission",
    website: "https://www.csac.ca.gov/cal-grants",
  },
  {
    id: "texas-grant",
    name: "TEXAS Grant",
    description: "Need-based grant for Texas residents",
    amount: "Up to $5,000",
    deadline: "March 15, 2025",
    type: "need-based",
    eligibility: ["Texas Resident", "Financial Need", "Enrolled 3/4 time"],
    states: ["TX"],
    colleges: ["ALL"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Texas Higher Education Coordinating Board",
    website: "https://www.thecb.state.tx.us/",
  },
  {
    id: "excelsior-scholarship",
    name: "Excelsior Scholarship",
    description: "Free tuition at SUNY and CUNY schools",
    amount: "Full Tuition",
    deadline: "July 21, 2025",
    type: "need-based",
    eligibility: ["New York Resident", "Income Under $125,000"],
    states: ["NY"],
    colleges: ["SUNY", "CUNY"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "New York State Higher Education Services Corporation",
    website: "https://www.hesc.ny.gov/",
  },
  {
    id: "bright-futures",
    name: "Bright Futures Scholarship",
    description: "Merit-based scholarship for Florida students",
    amount: "75% - 100% tuition",
    deadline: "August 31, 2025",
    type: "merit",
    eligibility: ["Florida Resident", "Academic Merit", "Community Service"],
    states: ["FL"],
    colleges: ["Florida Public Universities"],
    programs: ["ALL"],
    demographics: ["ALL"],
    provider: "Florida Department of Education",
    website: "https://www.floridastudentfinancialaidsg.org/",
  },
]

// Initialize with base scholarships and load CSV data
let scholarshipDatabase: ScholarshipData[] = [...baseScholarshipDatabase]
let csvScholarshipsLoaded = false
let seedsOfFortuneLoaded = false

// Function to load and merge all scholarship sources
export async function initializeScholarshipDatabase(): Promise<void> {
  if (csvScholarshipsLoaded && seedsOfFortuneLoaded) return

  try {
    console.log("Loading scholarships from all sources...")

    // Update existing scholarship dates first
    const updatedBaseScholarships = updateExistingScholarshipDates(baseScholarshipDatabase)
    scholarshipDatabase = [...updatedBaseScholarships]

    // Load original CSV scholarships if not already loaded
    if (!csvScholarshipsLoaded) {
      const csvScholarships = await loadScholarshipsFromCSV()
      const newCsvScholarships = csvScholarships.filter(
        (csvScholarship) => !isDuplicateScholarship(csvScholarship, scholarshipDatabase),
      )
      scholarshipDatabase = [...scholarshipDatabase, ...newCsvScholarships]
      csvScholarshipsLoaded = true
      console.log(`Added ${newCsvScholarships.length} scholarships from original CSV files`)
    }

    // Load Seeds of Fortune scholarships if not already loaded
    if (!seedsOfFortuneLoaded) {
      const seedsScholarships = await loadSeedsOfFortuneScholarships()
      const newSeedsScholarships = seedsScholarships.filter(
        (seedsScholarship) => !isDuplicateScholarship(seedsScholarship, scholarshipDatabase),
      )
      scholarshipDatabase = [...scholarshipDatabase, ...newSeedsScholarships]
      seedsOfFortuneLoaded = true
      console.log(`Added ${newSeedsScholarships.length} scholarships from Seeds of Fortune CSV files`)
    }

    console.log(`Total scholarships in database: ${scholarshipDatabase.length}`)
  } catch (error) {
    console.error("Error initializing scholarship database:", error)
  }
}

// Export the scholarship database (will be updated after CSV loading)
export { scholarshipDatabase }

// Rest of the existing functions remain the same
export interface ScholarshipFilters {
  location: string[]
  type: string[]
  amount: string[]
  deadline: string[]
  programs: string[]
  demographics: string[]
  eligibility: string[]
}

export function filterScholarships(
  scholarships: ScholarshipData[],
  filters: Partial<ScholarshipFilters>,
  searchQuery?: string,
): ScholarshipData[] {
  return scholarships.filter((scholarship) => {
    // Search query filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase()
      const matchesSearch =
        scholarship.name.toLowerCase().includes(query) ||
        scholarship.description.toLowerCase().includes(query) ||
        scholarship.provider.toLowerCase().includes(query)
      if (!matchesSearch) return false
    }

    // Location filter
    if (filters.location && filters.location.length > 0) {
      const hasLocationMatch = filters.location.some(
        (loc) => scholarship.states.includes(loc) || scholarship.states.includes("ALL"),
      )
      if (!hasLocationMatch) return false
    }

    // Type filter
    if (filters.type && filters.type.length > 0) {
      if (!filters.type.includes(scholarship.type)) return false
    }

    // Programs filter
    if (filters.programs && filters.programs.length > 0) {
      const hasProgramMatch = filters.programs.some(
        (prog) => scholarship.programs.includes(prog) || scholarship.programs.includes("ALL"),
      )
      if (!hasProgramMatch) return false
    }

    // Demographics filter
    if (filters.demographics && filters.demographics.length > 0) {
      const hasDemographicMatch = filters.demographics.some(
        (demo) => scholarship.demographics.includes(demo) || scholarship.demographics.includes("ALL"),
      )
      if (!hasDemographicMatch) return false
    }

    return true
  })
}

export function suggestScholarshipsForCollege(college: CollegeData): ScholarshipData[] {
  const suggestions: ScholarshipData[] = []

  // Add all scholarships and filter by relevance
  const allScholarships = [...scholarshipDatabase]

  const relevantScholarships = allScholarships.filter((scholarship) => {
    let relevanceScore = 0

    // State match (high priority)
    if (scholarship.states.includes(college.state) || scholarship.states.includes("ALL")) {
      relevanceScore += 10
    }

    // College name match
    if (scholarship.colleges.some((collegeName) => college.name.includes(collegeName))) {
      relevanceScore += 15
    }

    // Program match based on college characteristics
    if (college.engineeringPercent > 25 && scholarship.programs.includes("Engineering")) {
      relevanceScore += 8
    }
    if (college.businessPercent > 30 && scholarship.programs.includes("Business")) {
      relevanceScore += 8
    }

    // Institution type match
    if (college.ownership === 1 && scholarship.eligibility.some((req) => req.includes("Public"))) {
      relevanceScore += 5
    }
    if (college.ownership === 2 && scholarship.eligibility.some((req) => req.includes("Private"))) {
      relevanceScore += 5
    }

    // Need-based for high tuition schools
    if (college.tuitionOutState > 40000 && scholarship.type === "need-based") {
      relevanceScore += 6
    }

    // Merit-based for selective schools
    if (college.admissionRate && college.admissionRate < 20 && scholarship.type === "merit") {
      relevanceScore += 6
    }

    return relevanceScore >= 5 // Only include scholarships with decent relevance
  })

  // Sort by relevance and return top suggestions
  return relevantScholarships.slice(0, 15)
}

export function getScholarshipStats(scholarships: ScholarshipData[]) {
  const totalAmount = scholarships.reduce((sum, scholarship) => {
    const amount = scholarship.amount.match(/\$[\d,]+/)
    if (amount) {
      const numericAmount = Number.parseInt(amount[0].replace(/[$,]/g, ""))
      return sum + numericAmount
    }
    return sum
  }, 0)

  const typeDistribution = scholarships.reduce(
    (acc, scholarship) => {
      acc[scholarship.type] = (acc[scholarship.type] || 0) + 1
      return acc
    },
    {} as Record<string, number>,
  )

  return {
    totalScholarships: scholarships.length,
    totalAmount,
    typeDistribution,
  }
}
